#!/bin/bash

mysql=(mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" )

"${mysql[@]}" <<-EOSQL
            
      -- Standard notes
      CREATE DATABASE IF NOT EXISTS `${DB_DATABASE}`;
      CREATE USER '${DB_USERNAME}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
      GRANT ALL ON `${DB_DATABASE}`.* TO '${DB_USERNAME}'@'%';

      -- Passbolt
      CREATE DATABASE IF NOT EXISTS `${DATASOURCES_DEFAULT_DATABASE}`;
      CREATE USER '${DATASOURCES_DEFAULT_USERNAME}'@'%' IDENTIFIED BY '${DATASOURCES_DEFAULT_PASSWORD}';
      GRANT ALL ON `${DATASOURCES_DEFAULT_DATABASE}`.* TO '${DATASOURCES_DEFAULT_USERNAME}'@'%';

EOSQL