#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	SELECT 'CREATE DATABASE ${OUTLINE_DATABASE}' WHERE NOT EXISTS
		(SELECT FROM pg_database WHERE datname = '${OUTLINE_DATABASE}')\gexec
	SELECT 'CREATE USER ${OUTLINE_DB_USERNAME} WITH ENCRYPTED PASSWORD ''${OUTLINE_DB_PASSWORD}''' WHERE NOT EXISTS
		(SELECT FROM pg_catalog.pg_roles WHERE rolname = '${OUTLINE_DB_USERNAME}')\gexec
	GRANT ALL PRIVILEGES ON DATABASE ${OUTLINE_DATABASE} TO ${OUTLINE_DB_USERNAME};
	ALTER DATABASE ${OUTLINE_DATABASE} OWNER TO ${OUTLINE_DB_USERNAME};
EOSQL
