#!/bin/bash

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<- EOSQL

      -- Passbolt
      CREATE DATABASE IF NOT EXISTS \`${PASSBOLT_DATABASE}\`;
      CREATE USER '${PASSBOLT_DB_USERNAME}'@'%' IDENTIFIED BY '${PASSBOLT_DB_PASSWORD}';
      GRANT ALL ON \`${PASSBOLT_DATABASE}\`.* TO '${PASSBOLT_DB_USERNAME}'@'%';

      -- Davis
      CREATE DATABASE IF NOT EXISTS \`${DAVIS_DATABASE}\`;
      CREATE USER '${DAVIS_DB_USERNAME}'@'%' IDENTIFIED BY '${DAVIS_DB_PASSWORD}';
      GRANT ALL ON \`${DAVIS_DATABASE}\`.* TO '${DAVIS_DB_USERNAME}'@'%';

      -- Gitea
      CREATE DATABASE IF NOT EXISTS \`${GITEA_DATABASE}\` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';;
      CREATE USER IF NOT EXISTS '${GITEA_DB_USERNAME}'@'%' IDENTIFIED BY '${GITEA_DB_PASSWORD}';
      GRANT ALL ON \`${GITEA_DATABASE}\`.* TO '${GITEA_DB_USERNAME}'@'%';

EOSQL