#!/bin/bash

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<- EOSQL
            
      -- Standard notes
      CREATE DATABASE IF NOT EXISTS \`${NOTES_DATABASE}\`;
      CREATE USER '${NOTES_DB_USERNAME}'@'%' IDENTIFIED BY '${NOTES_DB_PASSWORD}';
      GRANT ALL ON \`${NOTES_DATABASE}\`.* TO '${NOTES_DB_USERNAME}'@'%';

      -- Passbolt
      CREATE DATABASE IF NOT EXISTS \`${PASSBOLT_DATABASE}\`;
      CREATE USER '${PASSBOLT_DB_USERNAME}'@'%' IDENTIFIED BY '${PASSBOLT_DB_PASSWORD}';
      GRANT ALL ON \`${PASSBOLT_DATABASE}\`.* TO '${PASSBOLT_DB_USERNAME}'@'%';

      -- Davis
      CREATE DATABASE IF NOT EXISTS \`${DAVIS_DATABASE}\`;
      CREATE USER '${DAVIS_DB_USERNAME}'@'%' IDENTIFIED BY '${DAVIS_DB_PASSWORD}';
      GRANT ALL ON \`${DAVIS_DATABASE}\`.* TO '${DAVIS_DB_USERNAME}'@'%';

EOSQL