#!/bin/bash

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<- EOSQL
            
      -- Standard notes
      CREATE DATABASE IF NOT EXISTS \`${NOTES_DATABASE}\`;
      CREATE USER '${NOTES_DB_USERNAME}'@'%' IDENTIFIED BY '${NOTES_DB_PASSWORD}';
      GRANT ALL ON \`${NOTES_DATABASE}\`.* TO '${NOTES_DB_USERNAME}'@'%';

      -- Passbolt
      CREATE DATABASE IF NOT EXISTS \`${PASSBOLT_DATABASE}\`;
      CREATE USER '${PASSBOLT_DB_USERNAME}'@'%' IDENTIFIED BY '${PASSBOLT_DB_PASSWORD}';
      GRANT ALL ON \`${PASSBOLT_DATABASE}\`.* TO '${PASSBOLT_DB_USERNAME}'@'%';

      -- Baïkal
      CREATE DATABASE IF NOT EXISTS \`${BAIKAL_DATABASE}\`;
      CREATE USER '${BAIKAL_DB_USERNAME}'@'%' IDENTIFIED BY '${BAIKAL_DB_PASSWORD}';
      GRANT ALL ON \`${BAIKAL_DATABASE}\`.* TO '${BAIKAL_DB_USERNAME}'@'%';

EOSQL